### ISSUE TITLE
When opening app for first time, the app shows a network error explanation.

### ISSUE THREAD

**Issue by EurigJones** [udacity/StockHawk#25]
I can't reproduce the following bug in the user feedback for Stockhawk:
> **Xaio-lu says:**
> "When I opened this app for the first time without a network connection, it was a confusing blank screen. I would love a message that tells me why the screen is blank or whether my stock quotes are out of date."

When loosing network connection with airplane mode or similar, on initial app install the first screen we come across is:

![screenshot_1489919235](https://cloud.githubusercontent.com/assets/2408619/24080081/532d1e00-0c8f-11e7-95f4-48b7232e77b3.png)

So essentially this is a bug to report that a bug doesn't happen!

**Comment by jwill** [comment]
Closing as the issue no longer applies, this is no longer a student project in the Android Nanodegree program.
