### ISSUE TITLE
Gradle 'StockHawk' project refresh failed Error:Cause: peer not authenticated. Android Studio throws this error while trying to build stockhawk

### ISSUE THREAD

**Issue by AbhirojPanwar** [udacity/StockHawk#9]

**Comment by JeremySilverTongue** [comment]
Hey, are you still getting this error on the latest version of master?

**Comment by JeremySilverTongue** [comment]
I think this was corrected in the latest version. Please reopen if that's not the case.

**Comment by ajibadeseun** [comment]
You can resolve this issue by following this link:
https://github.com/noveogroup/android-check
